export {default as Team} from './team';
export {default as Attend} from './attend';
export {default as Contact} from './contactus';
export {default as event1} from './event1';
export {default as event2} from './event2';
export {default as event3} from './event3';
export {default as Home} from './home';
export {default as Sponsers} from './sponsers';
export {default as Watch} from './watch';
